import type { Metadata } from 'next'
import { Shippori_Mincho, Noto_Sans_JP } from 'next/font/google'
import './globals.css'

const shipporiSans = Shippori_Mincho({
  variable: '--font-shippori-mincho',
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
})

const notoSansJP = Noto_Sans_JP({
  variable: '--font-noto-sans-jp',
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${shipporiSans.variable} ${notoSansJP.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
